### ISSUE TITLE
visual bug in new dashboard.

### ISSUE THREAD

**Issue by nosmaster89** [supertokens/dashboard#57] opened 2022-11-26 12:12 UTC
hovering over the user editing button hoving a few pixels to the right of the arrow causes the UI to start shifting left and right very quickly .

![IMG_20221126_120914](https://user-images.githubusercontent.com/87389996/204088257-a4d2d0ad-4a0b-48d1-86a6-668b18df04f3.jpg)

**Comment by rishabhpoddar** [comment] 2022-12-05 06:20
Closing this issue since we can't replicate it. Please feel free to reopen it with more info.

**Comment by nosmaster89** [comment] 2022-12-05 12:46
sorry just getting back round to this . ubuntu 22.04 using chrome Version 107.0.5304.121 (Official Build) (64-bit), in incog with no extensions. doesnt happen in firefox only in chrome

**Comment by rishabhpoddar** [comment] 2022-12-05 12:49
ok thanks! Useful info - will investigate

**Comment by nkshah2** [comment] 2022-12-12 06:19
Hi @nosmaster89,

Ive tried it with the same OS and chrome version and could not replicate the issue, could you give more information as to what exactly the issue is? More screenshots comparing normal state vs the problem state or a video would help

**Comment by rishabhpoddar** [comment] 2022-12-15 05:13
Since we still can't replicate this, im closing this issue

**Closed by rishabhpoddar** 2022-12-15 05:13 UTC
